config/routes.rb
Ludo::Application.routes.draw do
  resources :exercice_dynamiques

  resources :dynamiques

  resources :exercice_statiques

  resources :statiques

  resources :exercice_sujet_statiques

  resources :sujet_statiques

  resources :themes

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :corrections

  resources :exercices do
    member do
      get 'latec'
    end
  end

  resources :sujets

end

app/models/exercice_dynamique.rb
class ExerciceDynamique < ActiveRecord::Base
  belongs_to :dynamique
  belongs_to :exercice
  
  rails_admin do
    visible false
  end 
end

app/controllers/exercice_dynamiques_controller.rb
class ExerciceDynamiquesController < ApplicationController
  # GET /exercice_dynamiques
  # GET /exercice_dynamiques.json
  def index
    @exercice_dynamiques = ExerciceDynamique.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exercice_dynamiques }
    end
  end

  # GET /exercice_dynamiques/1
  # GET /exercice_dynamiques/1.json
  def show
    @exercice_dynamique = ExerciceDynamique.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exercice_dynamique }
    end
  end

  # GET /exercice_dynamiques/new
  # GET /exercice_dynamiques/new.json
  def new
    @exercice_dynamique = ExerciceDynamique.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exercice_dynamique }
    end
  end

  # GET /exercice_dynamiques/1/edit
  def edit
    @exercice_dynamique = ExerciceDynamique.find(params[:id])
  end

  # POST /exercice_dynamiques
  # POST /exercice_dynamiques.json
  def create
    @exercice_dynamique = ExerciceDynamique.new(params[:exercice_dynamique])

    respond_to do |format|
      if @exercice_dynamique.save
        format.html { redirect_to @exercice_dynamique, notice: 'Exercice dynamique was successfully created.' }
        format.json { render json: @exercice_dynamique, status: :created, location: @exercice_dynamique }
      else
        format.html { render action: "new" }
        format.json { render json: @exercice_dynamique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exercice_dynamiques/1
  # PUT /exercice_dynamiques/1.json
  def update
    @exercice_dynamique = ExerciceDynamique.find(params[:id])

    respond_to do |format|
      if @exercice_dynamique.update_attributes(params[:exercice_dynamique])
        format.html { redirect_to @exercice_dynamique, notice: 'Exercice dynamique was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exercice_dynamique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercice_dynamiques/1
  # DELETE /exercice_dynamiques/1.json
  def destroy
    @exercice_dynamique = ExerciceDynamique.find(params[:id])
    @exercice_dynamique.destroy

    respond_to do |format|
      format.html { redirect_to exercice_dynamiques_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/exercice_dynamiques_helper.rb
module ExerciceDynamiquesHelper
end

app/views/exercice_dynamiques/_form.html.erb
<%= form_for(@exercice_dynamique) do |f| %>
  <% if @exercice_dynamique.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercice_dynamique.errors.count, "error") %> prohibited this exercice_dynamique from being saved:</h2>

      <ul>
      <% @exercice_dynamique.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :exercice_id %><br />
    <%= f.number_field :exercice_id %>
  </div>
  <div class="field">
    <%= f.label :dynamique_id %><br />
    <%= f.number_field :dynamique_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercice_dynamiques/edit.html.erb
<h1>Editing exercice_dynamique</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercice_dynamique %> |
<%= link_to 'Back', exercice_dynamiques_path %>

app/views/exercice_dynamiques/index.html.erb
<h1>Listing exercice_dynamiques</h1>

<table>
  <tr>
    <th>Exercice</th>
    <th>Dynamique</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exercice_dynamiques.each do |exercice_dynamique| %>
  <tr>
    <td><%= exercice_dynamique.exercice_id %></td>
    <td><%= exercice_dynamique.dynamique_id %></td>
    <td><%= link_to 'Show', exercice_dynamique %></td>
    <td><%= link_to 'Edit', edit_exercice_dynamique_path(exercice_dynamique) %></td>
    <td><%= link_to 'Destroy', exercice_dynamique, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exercice dynamique', new_exercice_dynamique_path %>

app/views/exercice_dynamiques/new.html.erb
<h1>New exercice_dynamique</h1>

<%= render 'form' %>

<%= link_to 'Back', exercice_dynamiques_path %>

app/views/exercice_dynamiques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Exercice:</b>
  <%= @exercice_dynamique.exercice_id %>
</p>

<p>
  <b>Dynamique:</b>
  <%= @exercice_dynamique.dynamique_id %>
</p>


<%= link_to 'Edit', edit_exercice_dynamique_path(@exercice_dynamique) %> |
<%= link_to 'Back', exercice_dynamiques_path %>