config/routes.rb
Ludo::Application.routes.draw do
  resources :exercice_dynamiques

  resources :dynamiques

  resources :exercice_statiques

  resources :statiques

  resources :exercice_sujet_statiques

  resources :sujet_statiques

  resources :themes

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :corrections

  resources :exercices do
    member do
      get 'latec'
    end
  end

  resources :sujets

end

app/models/theme.rb
class Theme < ActiveRecord::Base
has_many :exercices

  def name
      self.intitule
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @themes }
    end
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
    @theme = Theme.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @theme }
    end
  end

  # GET /themes/new
  # GET /themes/new.json
  def new
    @theme = Theme.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @theme }
    end
  end

  # GET /themes/1/edit
  def edit
    @theme = Theme.find(params[:id])
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(params[:theme])

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render json: @theme, status: :created, location: @theme }
      else
        format.html { render action: "new" }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /themes/1
  # PUT /themes/1.json
  def update
    @theme = Theme.find(params[:id])

    respond_to do |format|
      if @theme.update_attributes(params[:theme])
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy

    respond_to do |format|
      format.html { redirect_to themes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<%= form_for(@theme) do |f| %>
  <% if @theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
      <% @theme.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :intitule %><br />
    <%= f.text_field :intitule %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/themes/edit.html.erb
<h1>Editing theme</h1>

<%= render 'form' %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

app/views/themes/index.html.erb
<h1>Listing themes</h1>

<table>
  <tr>
    <th>Intitule</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @themes.each do |theme| %>
  <tr>
    <td><%= theme.intitule %></td>
    <td><%= link_to 'Show', theme %></td>
    <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
    <td><%= link_to 'Destroy', theme, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Theme', new_theme_path %>

app/views/themes/new.html.erb
<h1>New theme</h1>

<%= render 'form' %>

<%= link_to 'Back', themes_path %>

app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Intitule:</b>
  <%= @theme.intitule %>
</p>


<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>