config/routes.rb
Ludo::Application.routes.draw do
  resources :exercice_dynamiques

  resources :dynamiques

  resources :exercice_statiques

  resources :statiques

  resources :exercice_sujet_statiques

  resources :sujet_statiques

  resources :themes

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :corrections

  resources :exercices do
    member do
      get 'latec'
    end
  end

  resources :sujets

end

app/models/exercice_statique.rb
class ExerciceStatique < ActiveRecord::Base
  belongs_to :statique
  belongs_to :exercice
  
  rails_admin do
    visible false
  end 
end

app/controllers/exercice_statiques_controller.rb
class ExerciceStatiquesController < ApplicationController
  # GET /exercice_statiques
  # GET /exercice_statiques.json
  def index
    @exercice_statiques = ExerciceStatique.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exercice_statiques }
    end
  end

  # GET /exercice_statiques/1
  # GET /exercice_statiques/1.json
  def show
    @exercice_statique = ExerciceStatique.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exercice_statique }
    end
  end

  # GET /exercice_statiques/new
  # GET /exercice_statiques/new.json
  def new
    @exercice_statique = ExerciceStatique.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exercice_statique }
    end
  end

  # GET /exercice_statiques/1/edit
  def edit
    @exercice_statique = ExerciceStatique.find(params[:id])
  end

  # POST /exercice_statiques
  # POST /exercice_statiques.json
  def create
    @exercice_statique = ExerciceStatique.new(params[:exercice_statique])

    respond_to do |format|
      if @exercice_statique.save
        format.html { redirect_to @exercice_statique, notice: 'Exercice statique was successfully created.' }
        format.json { render json: @exercice_statique, status: :created, location: @exercice_statique }
      else
        format.html { render action: "new" }
        format.json { render json: @exercice_statique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exercice_statiques/1
  # PUT /exercice_statiques/1.json
  def update
    @exercice_statique = ExerciceStatique.find(params[:id])

    respond_to do |format|
      if @exercice_statique.update_attributes(params[:exercice_statique])
        format.html { redirect_to @exercice_statique, notice: 'Exercice statique was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exercice_statique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercice_statiques/1
  # DELETE /exercice_statiques/1.json
  def destroy
    @exercice_statique = ExerciceStatique.find(params[:id])
    @exercice_statique.destroy

    respond_to do |format|
      format.html { redirect_to exercice_statiques_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/exercice_statiques_helper.rb
module ExerciceStatiquesHelper
end

app/views/exercice_statiques/_form.html.erb
<%= form_for(@exercice_statique) do |f| %>
  <% if @exercice_statique.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercice_statique.errors.count, "error") %> prohibited this exercice_statique from being saved:</h2>

      <ul>
      <% @exercice_statique.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :exercice_id %><br />
    <%= f.number_field :exercice_id %>
  </div>
  <div class="field">
    <%= f.label :statique_id %><br />
    <%= f.number_field :statique_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercice_statiques/edit.html.erb
<h1>Editing exercice_statique</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercice_statique %> |
<%= link_to 'Back', exercice_statiques_path %>

app/views/exercice_statiques/index.html.erb
<h1>Listing exercice_statiques</h1>

<table>
  <tr>
    <th>Exercice</th>
    <th>Statique</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exercice_statiques.each do |exercice_statique| %>
  <tr>
    <td><%= exercice_statique.exercice_id %></td>
    <td><%= exercice_statique.statique_id %></td>
    <td><%= link_to 'Show', exercice_statique %></td>
    <td><%= link_to 'Edit', edit_exercice_statique_path(exercice_statique) %></td>
    <td><%= link_to 'Destroy', exercice_statique, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exercice statique', new_exercice_statique_path %>

app/views/exercice_statiques/new.html.erb
<h1>New exercice_statique</h1>

<%= render 'form' %>

<%= link_to 'Back', exercice_statiques_path %>

app/views/exercice_statiques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Exercice:</b>
  <%= @exercice_statique.exercice_id %>
</p>

<p>
  <b>Statique:</b>
  <%= @exercice_statique.statique_id %>
</p>


<%= link_to 'Edit', edit_exercice_statique_path(@exercice_statique) %> |
<%= link_to 'Back', exercice_statiques_path %>