config/routes.rb
Ludo::Application.routes.draw do
  resources :exercice_dynamiques

  resources :dynamiques

  resources :exercice_statiques

  resources :statiques

  resources :exercice_sujet_statiques

  resources :sujet_statiques

  resources :themes

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :corrections

  resources :exercices do
    member do
      get 'latec'
    end
  end

  resources :sujets

end

app/models/exercice.rb
class Exercice < ActiveRecord::Base
  belongs_to :correction
  belongs_to :theme

  has_many :exercice_statiques
  has_many :statiques, :through => :exercice_statiques
  
  has_many :exercice_dynamiques
  has_many :dynamiques, :through => :exercice_dynamiques
  
  rails_admin do
    configure :statiques do
      visible false
    end
    configure :exercice_statiques do
      visible false
    end
    configure :dynamiques do
      visible false
    end
    configure :exercice_dynamiques do
      visible false
    end
  end
end

app/controllers/exercices_controller.rb
# encoding: UTF-8

class ExercicesController < ApplicationController
  # GET /exercices
  # GET /exercices.json
  def index
    @exercices = Exercice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exercices }
    end
  end

  # GET /exercices/1
  # GET /exercices/1.json
  def show
    @exercice = Exercice.find(params[:id])
    content = render_to_string(:template => "/exercices/show.pdf.erb", :layout => true)
    puts content
    puts "###################################################################"
    target  = "/var/www/ludo/public/pdf/temp.pdf"
    File.open(target, "w+") do |f|
      f.write(content)
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exercice }
      format.pdf { render pdf: @exercice }
    end
  end

  # GET /exercices/new
  # GET /exercices/new.json
  def new
    @exercice = Exercice.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exercice }
    end
  end

  # GET /exercices/1/edit
  def edit
    @exercice = Exercice.find(params[:id])
  end

  # POST /exercices
  # POST /exercices.json
  def create
    @exercice = Exercice.new(params[:exercice])

    respond_to do |format|
      if @exercice.save
        format.html { redirect_to @exercice, notice: 'Exercice was successfully created.' }
        format.json { render json: @exercice, status: :created, location: @exercice }
      else
        format.html { render action: "new" }
        format.json { render json: @exercice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exercices/1
  # PUT /exercices/1.json
  def update
    @exercice = Exercice.find(params[:id])

    respond_to do |format|
      if @exercice.update_attributes(params[:exercice])
        format.html { redirect_to @exercice, notice: 'Exercice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exercice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercices/1
  # DELETE /exercices/1.json
  def destroy
    @exercice = Exercice.find(params[:id])
    @exercice.destroy

    respond_to do |format|
      format.html { redirect_to exercices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/exercices_helper.rb
module ExercicesHelper
end

app/views/exercices/_form.html.erb
<%= form_for(@exercice) do |f| %>
  <% if @exercice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercice.errors.count, "error") %> prohibited this exercice from being saved:</h2>

      <ul>
      <% @exercice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bac %><br />
    <%= f.check_box :bac %>
  </div>
  <div class="field">
    <%= f.label :millesime %><br />
    <%= f.number_field :millesime %>
  </div>
  <div class="field">
    <%= f.label :theme %><br />
    <%= f.text_field :theme %>
  </div>
  <div class="field">
    <%= f.label :contenu %><br />
    <%= f.text_area :contenu %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercices/edit.html.erb
<h1>Editing exercice</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercice %> |
<%= link_to 'Back', exercices_path %>

app/views/exercices/index.html.erb
<h1>Listing exercices</h1>

<table>
  <tr>
    <th>Bac</th>
    <th>Millesime</th>
    <th>Theme</th>
    <th>Contenu</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exercices.each do |exercice| %>
  <tr>
    <td><%= exercice.bac %></td>
    <td><%= exercice.millesime %></td>
    <td><%= exercice.theme %></td>
    <td><%= exercice.contenu %></td>
    <td><%= link_to 'Show', exercice %></td>
    <td><%= link_to 'Edit', edit_exercice_path(exercice) %></td>
    <td><%= link_to 'Destroy', exercice, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exercice', new_exercice_path %>

app/views/exercices/new.html.erb
<h1>New exercice</h1>

<%= render 'form' %>

<%= link_to 'Back', exercices_path %>

app/views/exercices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Bac:</b>
  <%= @exercice.bac %>
</p>

<p>
  <b>Millesime:</b>
  <%= @exercice.millesime %>
</p>

<p>
  <b>Theme:</b>
  <%= @exercice.theme %>
</p>

<p>
  <b>Contenu:</b>
  <%= raw hesc @exercice.contenu %>
</p>
<iframe src="http://docs.google.com/viewer?url=http%3A%2F%2Fsheltered-coast-5239.herokuapp.com%2Fpdf%2Ftemp.pdf&embedded=true" width="600" height="780" style="border: none;"></iframe><%= link_to 'Back', exercices_path %>

app/views/exercices/show.pdf.erb
<%= raw @exercice.contenu %>